server:
  port: 9005
spring:
  application:
    name: shill-notify
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shill_guard?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: shillguard123
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: shillguard123
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.shillguard: debug
