server:
  port: 9002
spring:
  application:
    name: shill-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shill_guard?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: shillguard123
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: shillguard123
      database: 2
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true
logging:
  level:
    com.shillguard: debug
